url: "https://e4s-project-exp.io"
title: "E4S - Ecosystem for Science"
description: "Curated scientific libraries and tools for advanced scientific computing applications."
baseurl: ""
theme: "minimal-mistakes-jekyll"
logo: "/assets/images/e4s-logo.jpg"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
repository: "e4s-project-exp/e4s-project-exp.github.io"
repo_host: https://github.com

github_username: "maherou"